"""empty message

Revision ID: ee7bb8d16e02
Revises: 8af215472643
Create Date: 2017-10-14 20:17:48.000621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee7bb8d16e02'
down_revision = '8af215472643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('city', sa.String(), nullable=True))
    op.add_column('address', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'state')
    op.drop_column('address', 'city')
    # ### end Alembic commands ###
